export const name = 'dsh-computer-use-workflow-prompt';
export const inject = ['systemPrompt'];

export function apply(ctx) {
  return ctx.systemPrompt.section({
    name: 'dsh-computer-use-workflow', order: 108,
    text: [
      'Desktop and browser workflow protocol:',
      '- Choose browser DOM, visual, accessibility, keyboard, Windows Narrator, or targeted-window input according to the control, available evidence, and observed reliability.',
      '- browser_snapshot/browser_* indices, desktop image coordinates, native window_id and semantic element_id values are different evidence domains. Use identifiers from the matching observations in this session.',
      '- Refresh relevant observations when a change affects target identification, geometry or action state, or an attempted action leaves those states uncertain. Verify the relevant result. Window identities can be reused within their lifetime and are revalidated before control.',
      '- Native accessibility works without vision. Use computer_accessibility for a bounded overview, expand a root_element_id or continue next_cursor for large trees, and use computer_find(source:native) to query a window directly. Set max_matches for a few targets with a validated prefix. Partial coverage does not establish that a target is absent. Read detailed text/value/selection with computer_read.',
      '- Search names and roles may come from the task or the observed interface. Element and window identifiers must come from tool observations. Choose supported semantic operations according to actual capabilities; offscreen status alone does not prevent them.',
      '- For repeated native controls use computer_locate with an ordered container/target locator. Step where expressions combine all/any/not over properties of the same node; each leaf has exact/contains/.NET regex matching. Top-level fields also AND with where, and overlapping OR branches count one node once. Missing/null properties stay unknown under NOT; an unresolved predicate is a source error, never proof of absence. Invalid/limited/timed-out regex stops the call. Each step is unique unless nth is explicit; computer_wait re-resolves replacements within one deadline. computer_act sends one operation and optionally checks an after condition, reporting action execution separately from confirmation. Incomplete coverage cannot prove absence or uniqueness.',
      '- Windows computer_windows(operation:related) and locator window_query find visible new menu/popup/dialog roots from a fixed listed anchor. owned follows the native owner chain; explicit same_thread/same_process only prove correlation. Refine exact title (including an empty string) and class_name from observations. Multiple roots are ambiguous, partial window scans prove neither absence nor uniqueness. after.window_query can wait for a root opened by one action; an explicit after.window_id without a query reads that listed window directly. New semantic evidence is bound to the actual new root. Keep action status separate from the verified application result.',
      '- Windows computer_tree resolves a direct TreeItem path, expands only required ancestors once and independently confirms selection within one deadline. Replacing an observed branch stops the workflow; completed or unknown actions are not replayed. Prefer ItemContainer find_item/realize or computer_read(row,column) for virtual data: Grid.GetItem returns a separate cell_snapshot_id and can scroll the application. A Text cell may expose only grid_item, so select a freshly located row only when it supports selection_item. computer_scroll_find explicitly scrolls one pinned ScrollPattern container with page/scroll/total budgets and returns a geometrically intersecting item without activating it; exhausted or incomplete search does not prove global absence.',
      '- People may use the computer while automation runs. Keep the listed window identity pinned through waits and actions; do not redirect to a newly focused window. Revalidate evidence and check the result after concurrent edits, target replacement or focus changes. Unknown actions are not replayed. ItemContainer placeholders only allow realize, followed by a fresh observation.',
      '- Windows keyboard input accepts window_id or a window-bound snapshot_id without an image. computer_input executes bounded sequences, stops on failure and releases its held inputs. A timeout after dispatch may have an unknown result; verify it before repeating an action.',
      '- Windows computer_read_control reads bounded standard ListView rows from a fresh computer_windows(operation:children) child_window_id. It preserves focus/selection and rejects owner-data or unknown classes. Row/cell/UTF-16/message/total budgets can return a partial prefix; nextRow advances only after a complete row. A quarantined remote buffer forbids further allocation until the target process exits. This report is reading evidence, not screenshot or semantic action credentials.',
      '- Foreground image coordinates refer to that exact delivered screenshot. PrintWindow background images are application-rendered and cannot ground global pointer input. Use supported semantic controls or child HWND client coordinates for targeted messages and inspect foregroundChanged and the result.',
      '- computer_screenshot(output:file, save_to:...) saves PNG metadata without sending an image. This mode does not establish that the model viewed the image. Image delivery requires an image-capable route.',
      '- computer_find_image scans screen-resolution pixels and reports coverage, visitedPositions and totalPositions. Defaults are gray/no mask/template scale1; select color_mode:rgb, mask_mode:alpha with an inclusive alpha_min, or one explicit nearest-neighbor template_scale when needed. Alpha excludes pixels; it does not blend them. Result dimensions and activePixelCount describe the transformed template. Partial coverage cannot prove absence or uniqueness; computer_click_image requires complete coverage and one visual cluster. Nearby objects may share a cluster. Verify the application result after input.',
      '- computer_find_color, computer_ocr and computer_wait_visual require a bounded region in whole-window-relative native pixels with window_id, otherwise desktop pixels. They observe without focusing: screen needs an already-foreground window; print_window depends on application rendering. Counts are independent of samples, and partial output cannot establish absence. OCR reports recognized words/lines and bbox scale mapping; it can misread text, exposes no confidence scores and rejects min_confidence. Visual waits share one deadline and stop on capture/source errors. visual_id identifies a report, never screenshot or semantic action credentials.',
      '- Windows Narrator commands assume a running reader, Microsoft Standard layout and the chosen Insert/CapsLock modifier. Its virtual cursor, UIA focus and speech are separate: inputDelivered does not verify cursor movement or speech.',
    ].join('\n'),
  });
}
